### ISSUE TITLE
Ne trouve pas les saisons complètes

### ISSUE THREAD

**Issue by Maumtiesse** [rik91/script.quasar.burst-provider#1]
Tout d'abords, merci beaucoup pour les scripts, ils fonctionnent très bien pour ce qui est des films et des épisodes pour les 3 providers.

Pour faire une recherche saison complète, lorsque je suis sur une saison et que je clique droit sur saison 1 par exemple, le menu contextuel me propose de choisir un flux. Lors de la recherche sur les 3 providers, le script ne donne aucun résultat. 

De ce fait, sur les providers en question, pour des saisons plus anciennes, souvent les épisodes seuls n'existent plus et il ne reste en partage que des saisons complètes. Dans ce cas, en recherche sur un épisode, le script ne propose pas la saison complète et ne donne aucun résultat.

Encore merci pour ton super boulot !

**Comment by rik91** [comment]
Ah yes j'ai pas testé ce cas la.
Je regarde ça demain...

**Comment by Maumtiesse** [comment]
Super! Encore Bravo 😊

**Comment by rik91** [comment]
À mon avis il faut changer la valeur de season_keywords dans les fichier json et mettre "saison" au lieu de "Season"

**Comment by rik91** [comment]
Avec {title:fr} aussi ça doit être mieux

**Comment by Maumtiesse** [comment]
Ok je fais la modif. Mais là, je dois attendre car ma progéniture regarde un film sur ma rpi 3 et kodi... Ils seront vénèrent si j'interomps la seance!

**Comment by rik91** [comment]
Mdr. Je connais bien ça.
Tu as raison attend un peu sinon tu vas te faire lyncher...

**Comment by Maumtiesse** [comment]
Bon, j'ai fait la modif comme ceci 
"season_keywords": "{title:fr} Saison_{saison}",
"season_keywords2": "{title:fr} Saison{saison}",

Exemple pour une recherche du flux sur la saison 05, ça propose des résultats, mais pas uniquement pour la saison recherchée, il me propose n'importe quelles saisons de la série... S01, S 1, ou encore S02 S 2  etc ...

mmmm, on y est presque ;)

**Comment by rik91** [comment]
tu y était presque ! lol
il fallait pas changer le season entre accolade ({})
j'ai publier la correction !!!
Oublies pas de remettre tes identifiants et password pour yggtorrent.

**Comment by Maumtiesse** [comment]
Super. Je confirme fonctionne très bien pour les recherched de saisons complètes !
