### ISSUE TITLE
Aide ajout médiathèque

### ISSUE THREAD

**Issue by Maumtiesse** [rik91/script.quasar.burst-provider#2]

**Comment by Maumtiesse** [comment]
Bonjour Rik91.

Est il possible,  lorsque le script trouve une saison complète, de copier vers la médiathèque cette saison et télécharger chaque épisode toujours sur le même flux de saison. Ou est il possible de télécharger tout la saison ET de l'ajouter à la médiathèque. C'est utile en temps de freeleech et lorsqu'on souhaite regarder la série plus tard. Mais entre nous, je pense que c'est plutôt une option pour Quasar ...

**Comment by rik91** [comment]
Oui malheureusement, je n'ai pas la main la dessus avec les providers. C'est bien au niveau de Quasar qu'il faut que ça soit implémenté...
