### ISSUE TITLE
Installation sous android

### ISSUE THREAD

**Issue by JaqenGOT** [rik91/script.quasar.burst-provider#3]
Bonjour, j'aimerais faire l'installation des providers avec l'extension .json mais comment faire sous Android ou déplacer les fichiers. De plus ton idée de burst.fr serait top.Est-ce compliqué a mettre en place? En tout cas je te soutient dans ta démarche.

**Comment by rik91** [comment]
Tu peux trouver les différents emplacement du dossier userdata en fontion de l'OS utilisé ici : 
http://kodi.wiki/view/Userdata

Pour un burst.fr, il faut que je penche sur le problème.

**Comment by JaqenGOT** [comment]
Merci pour ta réactivité et impatient de voir le projet burst.fr se réaliser.

**Comment by rik91** [comment]
C'est bon tu as réussi à faire fonctionner les scripts ?

**Comment by JaqenGOT** [comment]
J'ai pas encore eu le temps de tester. Je te ferais un retour dés que c'est fait

**Comment by JaqenGOT** [comment]
Salut, j'ai ajouter les fichiers en créant le dossier providers mais j'ai un soucis avec quasar, quand je sélectionne in films ça mouline et aucun providers ne se lance et dans les paramètres.de quasar quand je vais sur providers ça mouline aussi et impossible d'y accéder. Ce problème est survenu d'un coup sans que je change quoi que se soit. Même en ajoutant t'es script c'est pareil. J'ai désactivée quasar puis je l'ai réactiver mais en vain. Merci de ton aide je comprend pas pourquoi du jour au lendemain impossible à lancer les providers

**Comment by rik91** [comment]
A priori ça vient de pas de mes scripts.
Il faudrait me fournir le log de Kodi (kodi.log) pour avoir plus de détail...

**Comment by JaqenGOT** [comment]
J'arrive à faire le log mais il ne se sauvegarde pas dans le chemin d'accès sous Android. Je ne trouve aucun fichier. J'ai pourtant bien fait la manip.

**Comment by JaqenGOT** [comment]
Sinon dis moi qu'elle ligne t'intéresse comme ça je  te la met en copie

**Comment by rik91** [comment]
Normalement y'a pas de manip spécial à faire, juste tu lances Kodi, les actions qui déconne et tu récupère le fichier
/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log

Après je peux pas te dire quelle ligne du fichier j'ai besoin.

Tu devrais peut être essayer de désinstaller et réinstaller complément Kodi...

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JaqenGOT** [comment]
Je n'ai rien dans le chemin d'accès Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
 Moi j'ai (en utilisant es explorer) Android/data/org.xbmc.kodi/files et rien d'autres. J'arrive pas à comprendre. Tu penses que ça peut venir de ma box android (xiaomi mi box3). Sinon je crois que je vais suivre ton conseil en réinstallant kodi.

**Comment by rik91** [comment]
Il faut que tu active "afficher les fichier caché" dans es explorer.

C'est une box Android ou Android TV ?

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JaqenGOT** [comment]
A ok je vais voir ça de suite. C'est une Android TV (MIBOX3), version Android 6.0.1

**Comment by JaqenGOT** [comment]
C'est bon tu avais raison, en activant les fichiers cachés j'ai réussis à voir le log.

**Comment by JaqenGOT** [comment]
voici le kodi.log:
[Kodi.pdf](https://github.com/rik91/script.quasar.burst-provider/files/1209663/Kodi.pdf)

**Comment by rik91** [comment]
A priori je vois pas de trace de chargement des providers. Mais as tu bien fait une requête sur un film avant de m'envoyer le log  parcequ'en fait à chaque démarrage de Kodi, un nouveau fichier log est créé et l'ancien effacé.

D'après ton log, tu a quand même pas mal d'extension installé sur ton Kodi.
Je serais toi je ferais une réinstallation propre avec uniquement les extensions que tu utilises vraiment.

**Comment by JaqenGOT** [comment]
Je vais refaire un log.effectivement celui que je t'ai envoyé dois être obsolète, et de même c'est vrai que j'ai pas mal d'extension, je vais faire un peu de nettoyage. LOL

**Comment by JaqenGOT** [comment]
Voila j’ai désinstallé pas mal d'extensions et j'ai refait un log. 
[kodi.log New.pdf](https://github.com/rik91/script.quasar.burst-provider/files/1212349/kodi.log.New.pdf)

**Comment by JaqenGOT** [comment]
je me suis trompé de fichier le bon est la:
[kodi .pdf](https://github.com/rik91/script.quasar.burst-provider/files/1212445/kodi.pdf)

**Comment by rik91** [comment]
Bon j'ai aussi une MiBox 3, j'ai testé de mettre les scripts et en effet ça fait pareil... je vais regarder...

**Comment by JaqenGOT** [comment]
C'est bizarre car ça marchait bien et sans que je touche a quoi que se soit ça s'est mis  a beugé. Tu pense que ça vient de la MIBOX3?

**Comment by rik91** [comment]
Je sais pas trop.

Quand tu lances Kodi, tu as pas une erreur du style :

Service de communication : echec du démarrage.

**Comment by JaqenGOT** [comment]
Oui oui exactement j'ai bien ce message a chaque démarrage de kodi. Ça  a un rapport avec quasar?

**Comment by rik91** [comment]
Avant je l'avais pas et j'avais pas de problème.
Et je sais que Quasar a besoin du service a distance, je pense que c'est lié.
C'est pas depuis que tu as cette erreur que Quasar fonctionne plus ?

**Comment by JaqenGOT** [comment]
Oui c'est ça, c'est bien depuis ce message que ça fonctionne actionné plus,

**Comment by JaqenGOT** [comment]
Bonsoir, tu as trouvé d'où venait le problème?

**Comment by rik91** [comment]
J'ai pas encore eu le temps de me pencher sur le problème...

**Comment by rik91** [comment]
Bon j'ai fait quelques tests.

Je pensais que c'était à cause de la mise à jour 17.3 de Kodi.
J'ai complètement désinstallé la 17.3 et la réinstaller, même soucis...
Du coup j'ai mis la 17.4 RC1, même soucis...
Je suis revenu en 17.2, même soucis...
J'ai même eu une mise a jour de la MiBox 3 (Correctif 1 Juillet 2017) que j'ai faites mais pas d'amélioration...

En cherchant "remote communication server failed to start", on trouve pas trop de truc récent et les vieux trucs parle de changer le port de communication du serveur... mais bon ça j'ai déjà essayer 20 000 fois, et ça change rien...

Bref, je sais plus trop ou chercher là...

**Comment by JaqenGOT** [comment]
Ok. En effet je pense pas que ça vient des version de kodi car cela marché sous la dernière version.(17.3). Ensuite j'ai aussi fait des recherche sur Google concernant ce «serveur de communication=échec de démarrage» et comme toi le seul truc que j'ai trouvé et qui date d 2015-2016 et par rapport au ports a changer, ce que j'ai fait et le résultat est le même. J'ai envoyé un message à scakemyer sur github a l'origine du script de Quasar(enfin je pense) il a de celà 5jours et toujours pas de réponse. Je crois qu'on est dans une impasse???
Faudrait tester sur une autre Android tv pour voir si c'est pas la MIBOX3 qui crée ce problème. Tu dis que la MIBOX3 a eu une mise à jours en juillet peut-être que c'est celle ci le problème car c'est dans ces environs que le problème est survenue.
Si d'autres personnes peut se pencher sur le problème n'hésitez pas.

**Comment by rik91** [comment]
La mise à jour de la Mibox je l'ai faites hier et avant ça fonctionnait pas donc c'est pas ça.

J'ai une Freebox mini 4K qui est aussi sous Android TV et le service démarre sans problème donc ça a l'air propre à la Mibox 3.

Sinon j'ai l'impression que le développement de Quasar est arrêté ou en suspens donc tu n'auras pas de réponse à ton message je pense...
Et pis c'est plus un problème lié à Kodi qu'à Quasar... C'est parceque le service de Kodi ne démarre pas que le système de Quasar ne fonctionne pas.

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JaqenGOT** [comment]
Ok. Et en fesant une réinstallation usine de la MIBOX? As-tu testé?

**Comment by rik91** [comment]
Nan pas testé, mais ça saoule un peu. Lol.
J'ai un collègue qui a une Mibox aussi je vais lui demander si il a le message mais pour le moment il est en vacances...

Sinon y'aura plus que ça a essayer...

**Comment by JaqenGOT** [comment]
Je te comprend ça rend fou. Lol j'attend le retour de ton collègue sinon d'ici là si je me sent je ferais le test. Et pour ton idée de Quasar Burst.fr franchement c'est a mettre en pratique.

**Comment by JaqenGOT** [comment]
Je viens de voir un truc dans les paramètres/ services/ contrôle. L'option autoriser le contrôle a distance par des programmes sur ce système était activé, jusque là normal mais je l'ai désactivé en me disant sué c'est peut-être un beug et bien je peux plus le reactiver, cela m'affiche «serveur de communication à distance= échec du démarrage.
Bon on en est toujours au même point mais au moins là on sait que c'est soit la MIBOX où peut-être Kodi????

**Comment by rik91** [comment]
Ouai je te rassure ça me fait la même chose pour le contrôle a distance...
A priori si il arrive pas a lancé le service c'est le port est utilisé... 
Sinon c'est peut être une autre application du store qui a été mise a jour et qui  bloque tout les ports... mais ça m'étonne. En plus j'ai pas installé énormément d'application.
Faudrait peut être voir quelle applications on a en commun...

**Comment by JaqenGOT** [comment]
Moi aussi j'ai pas beaucoup d'application.
. Retroarch
. Md.emu
. Netflix
. Kodi
. My canal
. Perfect player
. YouTube
. Jeuxvidéo.com
. Es explorateur
. Mx player pro
. vlc
. External Keyboard Helper

**Comment by rik91** [comment]
Désinstall Mycanal pour voir ?
ça semble avoir réglé le pb

**Comment by rik91** [comment]
Le suspens est insoutenable... réponds moi !!! lol

**Comment by JaqenGOT** [comment]
Putin je viens a peine de sortir. MDR. Je resterais en rentrant, patience.  C'est vrai que my canal beug a outrance en ce moment, j'ai beaucoup de message d'erreur et aucune chaine se lance. Je pensais que c'était a cause de l'on vpn mais appli en elle même n'est pas au point aussi.

**Comment by rik91** [comment]
pourquoi tu utilises un VPN ? tu n'es pas en France ?

**Comment by JaqenGOT** [comment]
Si si, je l'utilise quand je regarde des séries ou des films via quasar ou exodus.car on fait pas du vrai streaming c'est du torrent streaming donc j'utilise un vpn pour contourner hado....

**Comment by rik91** [comment]
ah ok je croyais que tu utilisais le VPN pour MyCanal

**Comment by JaqenGOT** [comment]
Du coup si c'est mycanal le fautif, je suis marron car je l'utile pour la TV du salon, si je dois le désinstaller j'ai plus de tv, il y a molotov mais j'ai un meilleur bouquet sur mycanal, bref déjà faut que je vois si chez moi c'est bien mycanal le problème

**Comment by rik91** [comment]
Oui faut déjà valider que c'est bien lui le problème...
Après ils vont peut être faire une mise a jour pour corriger chez Canal

**Comment by JaqenGOT** [comment]
Une question hors sujet as-tu déjà testé le fire stick de amazon? Il n'est pas commercialisé en France mais je sais qu'on peut installer des apk penses-tu que des appli comme mycanal fonctionnerait car je sais pas si le fire stick a des restrictions geographique?

**Comment by rik91** [comment]
Non je n'ai jamais testé le fire stick.
C'est pas mal, on peut installer Kodi dessus a priori... lol
Par contre pour MyCanal, vu comment ils ont du mal a faire des applis qui fonctionne bien sur des appareils testé, je doute que ça fonctionne bien sur le Fire Stick. Surtout que l'OS la dessus ça doit être du Android (pas TV) nan ?

**Comment by rik91** [comment]
une retour d'expérience là ...
https://www.amazon.fr/forum/kindle/ref=cm_cd_et_md_pl?_encoding=UTF8&cdForum=FxK9MV65I694XV&cdMsgID=MxNPXN676IKZ8H&cdMsgNo=9&cdPage=1&cdSort=oldest&cdThread=TxJ5XOY60HUBO5#MxNPXN676IKZ8H

**Comment by rik91** [comment]
a priori ça fonctionnerai mais bon... je préfère une Mibox pour quasi le même prix

**Comment by JaqenGOT** [comment]
Oui ke fire stick c'est android os pas tv. Je voulais m'en servir pour les chambres .C'est clair que la mibox est top hormis  sauf faible stockage et que j'ai galéré à faire reconnaître une clé usb pour m'en servir comme stockage. Je crois que c'est la version Android de la mibox qui block les accès de  lecture et écriture.( Ce qui est gênant aussi pour quasar dans les options impossible de choisir mon DD externe branché sur la freebox comme chemin d'accès pour la mise en cache des torrents, chose que je peux sur Kofi sur windows, bref ça c'est un autre soucis. Lol)si tu as une solution je prend. Lol

**Comment by rik91** [comment]
Pour le stockage j'ai jamais essayé...
Sinon tu as pu tester si en supprimant mycanal ça fonctionne ?

**Comment by JaqenGOT** [comment]
LOL, je suis en train de le faire...

**Comment by JaqenGOT** [comment]
Bingo.... ça fonctionne. C'était bien la dernière version de my canal qui fesait tout foirer.

**Comment by JaqenGOT** [comment]
Je vais voir si en installant la version anterieur de mycanal en apk et pas depuis le playstore si ça fonctionne avec quasar

**Comment by rik91** [comment]
Yeah saloperie de mycanal.
Bon moi je m'en servais plus de tte façon, j'ai plus d'identifiant valide :-(

**Comment by JaqenGOT** [comment]
Moi je l'utilise avec l'option de la freebox avec le bouquet panorama. En fait depuis que j'ai mon demo qui marche plus. J'ai cherché une alternative avec l IPTV mais c'est pas top. Soit ça freeze, soit ça coupe selon les fournisseurs.

**Comment by JaqenGOT** [comment]
Je vais encore t'embêter, j'arrive à  avoir les liens de nextorrent et torrent9 mais pour yggtorrent j'en ai aucun. Ça me dit toujours vides. Faut t'il que je désactivé quasar burst dans les providers de Quasar ou pas?

**Comment by rik91** [comment]
Ne surtout pas désactivé Quasar Burst.
As tu bien édité le fichier yggtorrent.json pour y mettre tes identifiants ?

**Comment by JaqenGOT** [comment]
Oui j'ai bien ajouté mon id et pass dans la ligne qui correspond, je viens de re vérifier. Au fait j'ai réinstallé mycanal et tout fonctionne. Va savoir???

**Comment by rik91** [comment]
Leur site est un peu en vrac en ce moment...
File un fichier de log pour voir ?
Cool pour MyCanal. Au moins si ça le refait, tu sauras quoi faire...

**Comment by JaqenGOT** [comment]
voici le log: 
[kodi - Bloc-notes.pdf](https://github.com/rik91/script.quasar.burst-provider/files/1236239/kodi.-.Bloc-notes.pdf)

**Comment by rik91** [comment]
WARNING: [script.quasar.burst] Status for 'https://yggtorrent.com/user/login' : 522
Ouai en fait en ce moment le site est down. 
Y'a un message sur la page d'accueil du site. 
On a juste accès à un snapshoot de leur site donc pas d'identification.

**Comment by JaqenGOT** [comment]
ok. j'ai vu ça, tu crois que le site est mort ou ils sont en train de changer de domaine?

**Comment by rik91** [comment]
nan je pense qu'ils ont juste un problème...
Tiens j'ai fait un premier jet de burst-fr
https://bitbucket.org/rik91/script.quasar.burst-fr/downloads/script.quasar.burst-fr.zip
Avec en prime t411.si en plus

**Comment by JaqenGOT** [comment]
Super. En plus j'allais t'en parler de t411.si et si ça vallait le coup d'en faire un script. Tu assures je vais le tester. Lol

**Comment by JaqenGOT** [comment]
alors j'ai installé le script et tout configuré. Dans les paramètres de quasar, j'ai désactivé tout les scripts et quasar burst et n'ai laissé d'activé que le Burst.fr. En sélectionnant un film il ne trouve aucun lien. Dois-je tout désactivé ou non?

**Comment by rik91** [comment]
Bizarre, je viens de tester sur ma Mibox, tout fonctionne nikel mise à part yggtorrent tjrs en vrac.
Il faut désactiver toutes les extensions programmes sauf quasar burst-fr et dans burst fr il faut choisir les sites que tu veux..

**Comment by JaqenGOT** [comment]
C'est bon ça fonctionne, fallait juste un redémarrage de la box. Dis moi les sites en DDL on peut en faire des scripts pour quasar? Si oui ce serait bien d'en rajouter dans le Burst.fr histoire d'avoir plus de choix. Qu'en penses-tu?

**Comment by rik91** [comment]
Et nan on peux pas Quasar est basé uniquement sur les torrents...

**Comment by JaqenGOT** [comment]
ok, par contre je sais que les gars derrière l'extension Vstream peuvent le faire sur leur addon. Si je trouve d'autres sites de torrents valable à rajouter sur Burst.fr je t'en ferais part. lol

**Comment by rik91** [comment]
a priori y'avais bien un problème avec yggtorrent.
ça a été corrigé.
Faut télécharger la nouvelle version
https://bitbucket.org/rik91/script.quasar.burst-fr/downloads/

Faudrait que je vois pour faire un repository pour avoir des mises à jour auto...

**Comment by JaqenGOT** [comment]
Cool, merci. Et bonne idée pour le repo.

**Comment by JaqenGOT** [comment]
Suite à la mise à jour automatique de Kodi en version 17.4 sur ma Android TV MIBoX3,  il m'est impossible depuis de lancer l'application kodi, crash sur crash.  Comme je sais que tu as aussi une mibox je voulais savoir si tu étais dans le même cas?

**Comment by rik91** [comment]
Non chez moi tout fonctionne à merveille !!

**Comment by rik91** [comment]
Envoi moi un log... Lol

**Comment by JaqenGOT** [comment]
LOL, je peux même pas envoyé un log, dès que je lance kodi ça m'affiche la page d'accueil et crash direct.

**Comment by rik91** [comment]
Il doit y avoir un fichier de log qui se crée dans /Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
Si tu y va avec es explorer ?

**Comment by JaqenGOT** [comment]
Ok, je t'envoie ça dès que je peux.

**Comment by JaqenGOT** [comment]
voici le kodi.log: 
[kodilog.pdf](https://github.com/rik91/script.quasar.burst-provider/files/1247313/kodilog.pdf)

**Comment by rik91** [comment]
Chelou je vois pas grand chose dans les logs....
Je te conseil de refaire une installation propre de Kodi.
Parce tu sais des fois quand on désinstalle un addons, ça désinstalle pas forcement tout ce qui a été installer à l'installation.

Exemple : sur une install fresh de Kodi, tu installes Vstream, ça t'installe d'autres extensions lors de l'installation genre Youtube. Bah si tu désinstalle Vstream,, Youtube sera pas désinstallé...

**Comment by JaqenGOT** [comment]
Je pense que c'est ce que Je vais faire. J'ai trop d'extension pour rien.

**Comment by JaqenGOT** [comment]
Le problème vient de la mise à jour de kodi 17.4 et l'extension PVR IPTV simple client qui font pas bon ménage.
