### ISSUE TITLE
Résultats YGGtorrent pas listés

### ISSUE THREAD

**Issue by Gregsr** [rik91/script.quasar.burst-provider#4]
Salut,

Les résultats de YGGtorrent ne sont plus listés (sous win7 et sous box minix android)
Voici mon .log https://we.tl/vRFAZ7yyQE

Peux-tu régler ce problème stp?

Merci,

Gregsr

**Comment by rik91** [comment]
C'est corrigé !!
Tu utilises les fichiers .json à copier à la main ou bien le pluggin burst-fr que j'ai fait ?
Parceque là j'ai corrigé dans les 2 mais je penses que je vais arrêter de maintenir les fichiers .json à mettre à la main...

**Comment by Gregsr** [comment]
Merci pour la correction rapide.
J'utilise le plugin burst-fr
